osx_image: xcode11.3
language: swift

xcode_workspace: gdgminsk.xcworkspace 
xcode_scheme: gdgminsk
xcode_destination: platform=iOS Simulator,OS=13.3,name=iPhone 11
podfile: Podfile

branches:
  only:
  - master

after_success:
  - bash <(curl -s https://codecov.io/bash) -J 'gdgminsk'
